# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 03:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.BigIntegerField(default=0)),
                ('version', models.IntegerField(default=0)),
                ('changeset', models.BigIntegerField(default=0)),
                ('uid', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('timestamp', models.DateTimeField()),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField()),
                ('feature_type', models.CharField(max_length=18)),
            ],
            managers=[
                ('geoobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=200)),
                ('reftype', models.CharField(max_length=200)),
                ('refrole', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='members',
            field=models.ManyToManyField(to='osmhistorynepal.Member'),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set([('feature_id', 'version', 'feature_type')]),
        ),
    ]
