# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 09:30
from __future__ import unicode_literals

from django.db import migrations
import django_hstore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osmhistorynepal', '0002_auto_20161107_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='tags',
            field=django_hstore.fields.DictionaryField(),
        ),
    ]
